name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Hanya berjalan saat ada push ke branch `main`

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/imageku:latest .

      - name: List Docker images
        run: docker images

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/imageku:latest

